dist: xenial
language: python
python:
  - "3.6"
before_install:
  - "if [[ -n $encrypted_3e74cccdb852_key || -n $encrypted_3e74cccdb852_iv ]]; then bash openssl aes-256-cbc -K $encrypted_3e74cccdb852_key -iv $encrypted_3e74cccdb852_iv -in test/api_keys.json.enc -out data/api_keys.json -d; fi"
  - "sudo apt-get install libre2-dev -y"
install:
  - "pip install pyflakes"
  - "git clone https://github.com/DesertBot/weercd.git"
  - "pip install Cython"
  - "pip install -r requirements.txt"
cache:
  - pip
script:
  - pyflakes start.py desertbot/
  - python test/comics.py
  - python weercd/weercd.py --file test/test_commands.txt -w 10.1 &
  - python start.py -c test/test_config.yaml -l DEBUG
notifications:
  email: false
