version: '3'

services:
  desertbot-server:
    image: starlitghost/desertbot
    container_name: desertbot-server
    build:
      context: .
      dockerfile: Dockerfile
    command: ["-c", "configs/server.yaml"]
    volumes:
      - ./configs:/app/configs
      - ./data:/app/data
      - ./logs:/app/logs
    logging:
      options:
        max-size: "1m"
        max-file: "10"
    restart: unless-stopped

# vim: tabstop=2 shiftwidth=2 expandtab
