# the bot's name
nickname: DesertBot
username: DesertBot
realname: DesertBot

# prefix for commands
commandChar: .

# where to find the bot's source
source: https://github.com/DesertBot/DesertBot/

# CTCP FINGER response
finger: GET YOUR FINGER OUT OF THERE

# slightly more privileged than admins; can add/remove admins
owners:
- "*!~TM@tyranicmoron.uk"
- "*!TM@tyranicmoron.uk"
- "*!Heufy@netadmin.dbcommunity.org"
- "*!hubbe@dbchat-d1d5c6a1.bb.dnainternet.fi"

# modules to load
modules:
- all
