# the bot's name
nickname: DesertBot
username: DesertBot
realname: DesertBot

# prefix for commands
commandChar: .

# where to find the bot's source
source: https://github.com/DesertBot/DesertBot/

# CTCP FINGER response
finger: GET YOUR FINGER OUT OF THERE

# slightly more privileged than admins; can add/remove admins
owners:
- "*!SG@45.55.60.209"
- "*!SG@starlitghost.xyz"
- "*!Heufy@netadmin.dbcommunity.org"
- "*!hubbe@hubbe.club"

# shelve storage settings
storage_save_interval: 60

# modules to load
modules:
- all
