# the bot's name
nickname: PyMoronBot
username: PyMoronBot
realname: PyMoronBot

# prefix for commands
commandChar: .

# where to find the bot's source
source: https://github.com/MatthewCox/PyMoronBot/

# CTCP FINGER response
finger: GET YOUR FINGER OUT OF THERE

# slightly more privileged than admins; can add/remove admins
owners:
- "*!~TM@tyranicmoron.uk"
- "*!TM@tyranicmoron.uk"

# modules to load
modules:
- all
# postprocesses to load
postprocesses:
- all

# aliases created with the Alias module
module-alias:
  aliases:
    aliases:
    - alias
    - list
    archwiki:
    - sub
    - '{var'
    - url
    - '{findurl'
    - site:wiki.archlinux.org/index.php
    - $0}}{slurp
    - text
    - $url
    - '#mw-content-text'
    - '>'
    - .mw-parser-output
    - '>'
    - p}
    - "\x0314|\x0F"
    - $url
    argwithdefault:
    - sed
    - s/^(\$[0-9]+)?$/$2/ic
    - $1
    aww:
    - redditimage
    - aww
    badum:
    - do
    - tish
    boardgame:
    - find
    - site:boardgamegeek.com
    - $0
    bobross:
    - twitch
    - bobross
    btc:
    - sub
    - '{var'
    - url
    - http://www.xe.com/currencyconverter/convert/?Amount=1&From=XBT&To}{slurp
    - text
    - $url=USD
    - .uccResultUnit}
    - /
    - '{slurp'
    - text
    - $url=EUR
    - .uccResultAmount}
    - EUR
    - /
    - '{slurp'
    - text
    - $url=GBP
    - .uccResultAmount}
    - GBP
    c:
    - choose
    cc:
    - currency
    censor:
    - sed
    - s/\w{2,}?(?:[^aeiou])(ing|ers|s|ed)\b/****\1/gio
    choice:
    - choose
    coinflip:
    - choose
    - Heads,
    - Tails
    cron:
    - schedule
    - cron
    - $0
    dbhours:
    - dbcalc
    - hours
    - $1
    dbmoney:
    - dbcalc
    - money
    - $1
    define:
    - sub
    - '{var'
    - url
    - https://www.google.co.uk/search?q=define:{sed
    - s/\s+/+/gc
    - $0}}{sed
    - s/.+does
    - not
    - select
    - a
    - tag
    - at.+/no
    - definition
    - for
    - "'$0'"
    - found/c
    - '{slurp'
    - text
    - $url
    - span[data-dobid="hdw"]}
    - ({slurp
    - text
    - $url
    - '.lr_dct_sf_h}):'
    - '{slurp'
    - text
    - $url
    - div[data-dobid="dfn"]}}
    dndstats:
    - sub
    - $sender's
    - D&D
    - stat
    - rolls
    - 'are:'
    - '{sed'
    - s/[^\(]*?\((\d+)\)[^\(]*/\1
    - /gc
    - '{rollv'
    - 4d6dl+4d6dl+4d6dl+4d6dl+4d6dl+4d6dl}}
    dogrates:
    - sub
    - '{choose'
    - Heckin,
    - H*ckin}
    - '{rolls'
    - d3+10}/10,
    - would
    - '{choose'
    - pet,
    - snug,
    - hug,
    - give
    - belly
    - rubs,
    - boop,
    - protec,
    - cherish,
    - treasure}.
    - "\x0314|\x0F"
    - '{redditimage'
    - dogpictures}
    down:
    - sub
    - '{slurp'
    - text
    - isup.me/{sed
    - s/https?:\/\///c
    - $0}
    - p}
    downforeveryoneorjustme:
    - down
    etym:
    - sub
    - '{var'
    - url
    - http://etymonline.com/index.php?searchmode=phrase&search=$1}{var
    - index
    - nth-of-type({argwithdefault
    - $2
    - "1})}\x02{slurp"
    - text
    - $url
    - "dt:$index}:\x0F"
    - '{slurp'
    - text
    - $url
    - dd:$index}
    - "\x0314|\x0F"
    - '{googl'
    - http://etymonline.com{slurp
    - href
    - $url
    - dt:$index
    - a}}
    findurl:
    - sub
    - '{sed'
    - s/^.*\|.+(http.+?$)/\1/c
    - '{find'
    - $0}}
    ignorelist:
    - ignore
    - list
    in:
    - remindme
    isdown:
    - isup
    isup:
    - down
    kickstarter:
    - ks
    ks:
    - sub
    - '{urlfollow'
    - '{findurl'
    - site:kickstarter.com/projects/
    - $0}}
    - "\x0314|\x03"
    - $urlfollowURL
    'null':
    - sed
    - s/.*//c
    - $0
    patreon:
    - sub
    - '{patreondata'
    - '{argwithdefault'
    - $0
    - loadingreadyrun}}{var
    - c
    - '{sed'
    - s/\s+\|\s+Patreon//c
    - '{slurp'
    - text
    - $u
    - title}}}{sed
    - s/.*Problem
    - fetching.*/'$0'
    - doesn't
    - appear
    - to
    - have
    - a
    - patreon/c
    - $c
    - '|'
    - $p
    - patrons
    - are
    - pledging
    - $s
    - per
    - $t
    - '|'
    - $slurpURL}
    patreondata:
    - sub
    - '{var'
    - u
    - patreon.com/$0}{var
    - d
    - '{slurp'
    - text
    - $u
    - script}}{var
    - s
    - '{rolls'
    - '{sed'
    - 's/.*"pledge_sum":'
    - (\d+)(.|\n)*/\1/c
    - $d}/100}}{var
    - t
    - '{sed'
    - 's/.*"pay_per_name":'
    - '"([^"]+)(.|\n)*/\1/c'
    - $d}}{var
    - p
    - '{sed'
    - 's/.*"patron_count":'
    - (\d+),\s+"pay(.|\n)*/\1/c
    - $d}}
    peopleinspace:
    - sub
    - '{sed'
    - s/.*"number"\s*:\s*(\d+).*/\1/c
    - '{slurp'
    - text
    - http://www.howmanypeopleareinspacerightnow.com/peopleinspace.json
    - html}}
    pick:
    - choose
    r:
    - roll
    remindme:
    - sub
    - '{null'
    - '{delay'
    - $1
    - say
    - '[Reminder]'
    - '$sender:'
    - $2+}}OK,
    - I'll
    - send
    - you
    - a
    - reminder
    - in
    - $delayString
    rolls:
    - sub
    - '{null'
    - '{roll'
    - $0}}$rollTotal
    s2+:
    - sed
    - s/\s+/+/gc
    - $0
    search:
    - find
    share:
    - sub
    - '{var'
    - url
    - https://www.google.com/search?q={say
    - $1}+share+price}{slurp
    - text
    - $url
    - '.vk_h}:'
    - '{slurp'
    - text
    - $url
    - .fac-l}
    - '{slurp'
    - text
    - $url
    - .fac-cc}
    showalias:
    - alias
    - show
    steam:
    - sub
    - '{urlfollow'
    - '{sed'
    - s/agecheck\///ic
    - '{find'
    - site:store.steampowered.com/app/
    - $0}}}
    - "\x0314|\x03"
    - $urlfollowURL
    steamspy:
    - sub
    - '{var'
    - j
    - jq
    - '{sed'
    - s/app\//api.php?request=appdetails&appid=/c
    - '{findurl'
    - site:steamspy.com/app/
    - $0}}
    - .}{$j["name"]}
    - "\x0314|\x0F"
    - 'Owners:'
    - "{$j[\"owners\"]}\x0314±{$j[\"owners_variance\"]}"
    - "|\x0F"
    - Peak
    - Players
    - 'Yesterday:'
    - '{$j["ccu"]}'
    - "\x0314|\x0F"
    - Last
    - '2'
    - 'weeks:'
    - "{$j[\"players_2weeks\"]}\x0314±{$j[\"players_2weeks_variance\"]}\x0F"
    timer:
    - sub
    - '{null'
    - '{delay'
    - $1
    - say
    - $sender,
    - your
    - $delayString
    - timer
    - is
    - up!}}$sender,
    - a
    - timer
    - has
    - been
    - started
    - for
    - $delayString!
    tvtropes:
    - sub
    - '{var'
    - url
    - '{findurl'
    - site:tvtropes.org/pmwiki/pmwiki.php/Main/
    - $0}}{slurp
    - text
    - $url
    - .page-title}
    - "\x0314|\x0F"
    - '{slurp'
    - content
    - $url
    - meta[property=og:description]}
    - "\x0314|\x0F"
    - $url
    twitch:
    - sub
    - '{urlfollow'
    - '{sed'
    - s/\.tv\/(?:p|settings|customer|(\w+))\/(?:.+?)?$/.tv\/\1\//c
    - '{findurl'
    - site:www.twitch.tv/
    - '{argwithdefault'
    - $1
    - loadingreadyrun}}}}
    - "\x0314|\x0F"
    - $urlfollowURL
    ualias:
    - sub
    - '{null'
    - '{alias'
    - del
    - $1}}{alias
    - add
    - $0}
    umlaut:
    - sed
    - s/([aeiou])/\1̈/gi
    unalias:
    - alias
    - del
    - $0
    unignore:
    - ignore
    - del
    up:
    - down
    wiki:
    - sub
    - '{var'
    - url
    - '{findurl'
    - site:en.wikipedia.org
    - $0}}{sed
    - s/\[(‡\s)?\d+\]//cg
    - '{slurp'
    - text
    - $url
    - '#mw-content-text'
    - p}}
    - "\x0314|\x0F"
    - '{slurp'
    - href
    - $url
    - link[rel="canonical"]}
    wikipedia:
    - wiki
    wikirandom:
    - sub
    - '{wiki'
    - '{slurp'
    - href
    - https://en.wikipedia.org/wiki/Special:Random
    - link[rel="canonical"]}}
    xkcd:
    - sub
    - '{sed'
    - "s/\x0314\\|(.*)\x0314\\|/\x0314|\x03/c"
    - '{find'
    - site:xkcd.com
    - $0}}
    youtube:
    - sub
    - '{urlfollow'
    - '{sed'
    - s/.*?(http:\/\/[^\s]+?)$/\1/ic
    - '{findurl'
    - site:youtube.com/watch
    - $0}}}
    - "\x0314|\x03"
    - $urlfollowURL
    yt:
    - youtube
  help:
    censor: '"Censors" your filthy language'
    remindme: 'remindme <duration> <message> - highlights you with <message> after
      <duration> has passed. Duration supports (w)eeks, (d)ays, (h)ours, (m)inutes,
      (s)econds. Example usage: .remindme 1h30m something is happening!'
    rolls: Rolls the given dice (as in roll), but only returns the result total
    ualias: ualias <alias> <command> - updates <alias> with a new command to execute
      (requires bot admin permissions)
    umlaut: umlaut - adds umlauts to all the vowels of the previous message. Why you
      ask? What a silly question
    unalias: unalias <alias names> - deletes the specified aliases (requires bot admin
      permissions)
    xkcd: xkcd <search term> - returns the top result for the given search term from
      xkcd.com
    youtube: youtube/yt <search term> - returns the top video for the given search
      term from youtube.com
    yt: youtube/yt <search term> - returns the top video for the given search term
      from youtube.com
