nickname: "PyMoronBot"
username: "PyMoronBot"
realname: "PyMoronBot"

commandChar: "."

source: "https://github.com/MatthewCox/PyMoronBot/"
finger: "GET YOUR FINGER OUT OF THERE"

admins:
- "*!TM@tyranicmoron.uk"